<?php

declare(strict_types=1);

namespace Pl8r\Component\Jurisdiction;

/**
 * @psalm-type Subdivisions = array<string, list{?string, bool}>
 * @psalm-type Countries = array<string, list{0: ?string, 1: bool, 2?: Subdivisions}>
 */
final readonly class JurisdictionRepository
{
  public const KEY_VRI = 0;
  public const KEY_COUNTRY_HIDE = 1;
  public const KEY_SUBDIVISION_USE_ISO = 1;
  public const KEY_COUNTRY_SUBDIVISIONS = 2;

  /**
   * [ID => [?VRI, hide_in_ui, ?[subdivision_ID => [?VRI, use_iso3166]]]].
   *
   * @var array<string,mixed>
   *
   * @psalm-var Countries
   */
  public array $jurisdictions;

  public function __construct()
  {
    $this->jurisdictions = [
      '?A' => ['ABH', false],
      '?D' => ['DPR', false],
      '?L' => ['LPR', false],
      '?N' => ['TODO NORTHERN CYPRUS', false],
      '?O' => ['RSO', false],
      'AD' => ['AND', false],
      'AE' => ['UAE', false],
      'AF' => ['AFG', false],
      'AG' => ['AG', false],
      'AL' => ['AL', false],
      'AM' => ['AM', false],
      'AO' => ['ANG', false],
      'AR' => ['RA', false],
      'AT' => ['A', false],
      'AU' => ['AUS', true, [
        'ACT' => [null, false],
        'CC' => [null, true],
        'CX' => [null, true],
        'NI' => [null, false],
        'NSW' => [null, false],
        'NT' => [null, false],
        'QLD' => [null, false],
        'SA' => [null, false],
        'TAS' => [null, false],
        'VIC' => [null, false],
        'WA' => [null, false],
        'ZZZ' => [null, false],
      ]],
      'AZ' => ['AZ', false],
      'BA' => ['BIH', false],
      'BB' => ['BDS', false],
      'BD' => ['BD', false],
      'BE' => ['B', false],
      'BF' => ['BF', false],
      'BG' => ['BG', false],
      'BH' => ['BRN', false],
      'BI' => ['RU/BU*', false],
      'BJ' => ['DY/RB*', false],
      'BN' => ['BRU', false],
      'BO' => ['BOL', false],
      'BR' => ['BR', false],
      'BS' => ['BS', false],
      'BT' => ['BHT', false],
      'BW' => ['BW', false],
      'BY' => ['BY', false],
      'BZ' => ['BH', false],
      'CA' => ['CDN', true, [
        'AB' => [null, false],
        'BC' => [null, false],
        'MB' => [null, false],
        'NB' => [null, false],
        'NL' => [null, false],
        'NS' => [null, false],
        'NT' => [null, false],
        'NU' => [null, false],
        'ON' => [null, false],
        'PE' => [null, false],
        'QC' => [null, false],
        'SK' => [null, false],
        'YT' => [null, false],
        'ZFR' => [null, false],
      ]],
      'CD' => ['CGO', false],
      'CF' => ['RCA', false],
      'CG' => ['RCB/RC*', false],
      'CH' => ['CH', false],
      'CI' => ['CI', false],
      'CL' => ['RCH', false],
      'CM' => ['CAM/CMR*', false],
      'CN' => ['CHN', false, [
        'HK' => ['HK', true],
        'MO' => ['MO', true],
      ]],
      'CO' => ['CO', false],
      'CR' => ['CR', false],
      'CU' => ['CU', false],
      'CV' => ['CV', false],
      'CY' => ['CY', false],
      'CZ' => ['CZ', false],
      'DD' => ['DDR', false],
      'DE' => ['D', false],
      'DJ' => ['DJI', false],
      'DK' => ['DK', false, [
        'FO' => ['FO', true],
      ]],
      'DM' => ['WD', false],
      'DO' => ['DOM', false],
      'DZ' => ['DZ', false],
      'EC' => ['EC', false],
      'EE' => ['EST', false],
      'EG' => ['EG', false],
      'EH' => [null, false],
      'ER' => ['ER', false],
      'ES' => ['E', false],
      'ET' => ['ETH', false],
      'FI' => ['FIN', false],
      'FJ' => ['FJI', false],
      'FM' => ['FSM', false],
      'FR' => ['F', false],
      'GA' => ['G/RG*', false],
      'GB' => ['UK/GB', false, [
        'GB-?A' => ['GBA', false],
        'AI' => [null, true],
        'BM' => [null, true],
        'FK' => [null, true],
        'GG' => ['GBG', true],
        'GI' => ['GBZ', true],
        'IM' => ['GBM', true],
        'IO' => [null, true],
        'JE' => ['GBJ', true],
        'KY' => [null, true],
        'MS' => [null, true],
        'PN' => [null, true],
        'SH' => [null, true],
        'TC' => [null, true],
        'VG' => ['BVI', true],
      ]],
      'GD' => ['WG', false],
      'GE' => ['GE', false],
      'GH' => ['GH', false],
      'GM' => ['WAG', false],
      'GN' => ['RG', false],
      'GQ' => ['GE*', false],
      'GR' => ['GR', false],
      'GT' => ['GCA', false],
      'GW' => ['RGB', false],
      'GY' => ['GUY', false],
      'HN' => ['HN', false],
      'HR' => ['HR', false],
      'HT' => ['RH', false],
      'HU' => ['H', false],
      'ID' => ['RI', false],
      'IE' => ['IRL', false],
      'IL' => ['IL', false],
      'IN' => ['IND', false],
      'IQ' => ['IRQ', false, [
        'KR' => ['IRQ KR', false],
      ]],
      'IR' => ['IR', false],
      'IS' => ['IS', false],
      'IT' => ['I', false],
      'JE' => ['GBJ', false],
      'JM' => ['JA', false],
      'JO' => ['HKJ', false],
      'JP' => ['J', false],
      'KE' => ['EAK', false],
      'KG' => ['KG', false],
      'KH' => ['KH', false],
      'KI' => ['KIR', false],
      'KM' => ['COM', false],
      'KN' => ['KN', false],
      'KP' => [null, false],
      'KR' => ['ROK/KOR*', false],
      'KW' => ['KWT', false],
      'KZ' => ['KZ', false],
      'LA' => ['LAO', false],
      'LB' => ['RL', false],
      'LC' => ['WL', false],
      'LI' => ['FL', false],
      'LK' => ['CL', false],
      'LR' => ['LB', false],
      'LS' => ['LS', false],
      'LT' => ['LT', false],
      'LU' => ['L', false],
      'LV' => ['LV', false],
      'LY' => ['LAR/LY*', false],
      'MA' => ['MA', false],
      'MC' => ['MC', false],
      'MD' => ['MD', false, [
        '?T' => [null, false],
      ]],
      'ME' => ['MNE', false],
      'MG' => ['RM', false],
      'MH' => ['MH', false],
      'MK' => ['NMK', false],
      'ML' => ['RMM', false],
      'MM' => ['BUR', false],
      'MN' => ['MGL/MNG*', false],
      'MR' => ['RIM', false],
      'MT' => ['M', false],
      'MU' => ['MS', false],
      'MV' => ['MV', false],
      'MW' => ['MW', false],
      'MX' => ['MEX', false],
      'MY' => ['MAL', false],
      'MZ' => ['MOC', false],
      'NA' => ['NAM', false],
      'NE' => ['RN', false],
      'NG' => ['WAN', false],
      'NI' => ['NIC', false],
      'NL' => ['NL', false, [
        'NL-AW' => [null, true],
        'NL-BQ' => ['BQ', true],
        'NL-CW' => ['CW', true],
        'NL-SX' => ['SX', true],
      ]],
      'NO' => ['N', false],
      'NP' => ['NEP', false],
      'NR' => ['NAU', false],
      'NZ' => ['NZ', false, [
        'CK' => [null, true],
        'NU' => [null, true],
      ]],
      'OM' => ['OM', false],
      'PA' => ['PA', false],
      'PE' => ['PE', false],
      'PG' => ['PNG', false],
      'PH' => ['RP', false],
      'PK' => ['PK', false],
      'PL' => ['PL', false],
      'PS' => ['P*', false],
      'PT' => ['P', false],
      'PW' => ['PAL', false],
      'PY' => ['PY', false],
      'QA' => ['Q', false],
      'RO' => ['RO', false],
      'RS' => ['SRB', false],
      'RU' => ['RUS', false],
      'RW' => ['RWA', false],
      'SA' => ['KSA', false],
      'SB' => ['SOL', false],
      'SC' => ['SY', false],
      'SD' => ['SUD', false],
      'SE' => ['S', false],
      'SG' => ['SGP', false],
      'SI' => ['SLO', false],
      'SK' => ['SK', false],
      'SL' => ['WAL/SLE*', false],
      'SM' => ['RSM', false],
      'SN' => ['SN', false],
      'SO' => ['SO', false, [
        '?S' => [null, false],
      ]],
      'SR' => ['SME', false],
      'SS' => [null, false],
      'ST' => ['STP', false],
      'SU' => ['SU', false],
      'SV' => ['ES', false],
      'SY' => ['SYR', false],
      'SZ' => ['SD', false],
      'TD' => ['TCH', false],
      'TG' => ['TG', false],
      'TH' => ['T', false],
      'TJ' => ['TJ', false],
      'TL' => ['TL', false],
      'TM' => ['TM', false],
      'TN' => ['TN', false],
      'TO' => ['TO', false],
      'TR' => ['TR', false],
      'TT' => ['TT', false],
      'TV' => ['TUV', false],
      'TW' => ['RC', false],
      'TZ' => ['EAT', false, [
        'TZ-1' => ['EAZ', false],
      ]],
      'UA' => ['UA', false],
      'UG' => ['EAU', false],
      'US' => ['USA', true, [
        'ZZC' => [null, false],
      ]],
      'UY' => ['ROU', false],
      'UZ' => ['UZ', false],
      'VA' => ['V', false],
      'VC' => ['WV', false],
      'VE' => ['YV', false],
      'VN' => ['VN', false],
      'VU' => ['VU', false],
      'WS' => ['WS', false],
      'XK' => ['RKS', false],
      'YE' => ['YAR', false],
      'YU' => ['YU', false],
      'ZA' => ['ZA', false],
      'ZM' => ['Z/ZM*', false],
      'ZW' => ['ZW', false],
    ];
  }
}
